/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chair.gltf 
Author: Tyron (https://sketchfab.com/Omty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/barber-chair-6458816e73534df0a26ddc6567395d2c
Title: Barber Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chair.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Leather} scale={0.85}/>
        <mesh geometry={nodes.Object_3.geometry} material={materials.Metal} scale={0.85}/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Plastic} scale={0.85}/>
      </group>
    </group>
  )
}

useGLTF.preload('/chair.gltf')
